wandb_version: 1

hidden_dim:
  desc: null
  value: 1
num_hidden_linear:
  desc: null
  value: 50
epochs:
  desc: null
  value: 3
batchsize:
  desc: null
  value: 40
learning_rate:
  desc: null
  value: 0.0001
_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1718638589
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.9
      5: 0.17.1
      8:
      - 1
      - 5
      13: linux-x86_64
